#!/usr/bin/bash
ping -c 4 archlinux.org

timedatectl set-ntp true

ls -l /sys/firmware/efi/efivars

( echo 'o'
echo 'y'
echo 'n'
echo ''
echo ''
echo '+512M'
echo 'ef00'
echo 'n'
echo ''
echo ''
echo '+4G'
echo '8200'
echo 'n'
echo ''
echo ''
echo ''
echo ''
echo 'w'
echo 'y' ) | gdisk /dev/sda

lsblk

mkfs.fat /dev/sda1
mkswap /dev/sda2
mkfs.ext4 /dev/sda3

mount /dev/sda3 /mnt
mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi
swapon /dev/sda2

pacstrap /mnt base base-devel linux linux-firmware linux-headers grub efibootmgr intel-ucode xf86-video-intel iwd networkmanager network-manager-applet man bash-completion nano vim gdm gnome gnome-tweaks firefox termite alacritty

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt

echo 'Funcionou mpt!!!'
